resources:
  - https://github.com/crenshaw-dev/metrics//config/?ref=kind
  - argo-cd

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 41.7.4
    namespace: monitoring
    releaseName: "test"
    includeCRDs: true
